[versions]
# Build & SDKs
agp = "8.11.2"
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
kotlin = "2.2.20"
ksp = "2.1.10-1.0.29"

# Core Frameworks
composeMultiplatform = "1.8.2"
navigation = "2.9.0-beta01"
buildkonfig = "0.15.2"

# Others dependencies
androidx-activity = "1.12.2"
androidx-lifecycle = "2.9.3"
apollo = "4.1.0"
coroutines = "1.10.1"
koin = "4.1.1"
koin-annotations-bom = "1.4.0"
koinTest = "4.1.1"
ktor = "3.0.3"
serialization = "1.7.3"
splash = "1.0.1"

# Tests
uiTest = "1.10.0"
turbine = "1.2.1"
kotlinx-coroutines-test = "1.8.0"

[libraries]
# --- ANDROID & UI CORE ---
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation" }
splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "splash" }

# --- DEPENDENCY INJECTION (KOIN) ---
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations-bom" }

# --- NETWORKING & DATA ---
# Apollo (GraphQL)
apollo-runtime = { module = "com.apollographql.apollo:apollo-runtime" }
apollo-normalized-cache = { module = "com.apollographql.apollo:apollo-normalized-cache" }
# Ktor & Serialization
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

# --- ASYNC & COROUTINES ---
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# --- TEST ---
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-annotations_common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinTest" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "uiTest" }

[plugins]
# Android & Kotlin Base
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

# Compose Specific
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

# Tools & Generators
apollo = { id = "com.apollographql.apollo", version.ref = "apollo" }
buildkonfig_plugin = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }